# Generated by Django 5.0.1 on 2024-03-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcenter',
            name='specialty',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
