# Generated by Django 5.0.1 on 2024-04-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_message_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
