# Generated by Django 5.0.1 on 2024-03-29 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chat_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chatbot.user'),
        ),
    ]
