# Generated by Django 5.0.1 on 2024-03-29 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_message_id_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Symptoms',
            new_name='Symptom',
        ),
    ]
