# Generated by Django 5.0.2 on 2024-05-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_chat_user_alter_medicalappointment_specialist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='embspecialist',
            field=models.BinaryField(default=b'\x00'),
        ),
    ]
